s = "Python"
print(s)
print(s[::-1])
print(s[-5:-2:-1])
print(len(s),s)
print(s[-4])
print(s[-1])
print(s[5])
print(s[-3])
print(s[-5:-2])
print(s[-4:-1])
print(s[-6:-3])
print(s[ :-2])
print(s[-3: ])
print(s[-3:-6])
print(s[ ::-2])
print(s[ ::-1])
print(s[-5:-2:-1])
print(s[-5::-1])
print(s[-2::-2])
print(s[-4::-1])
print(s[ :-4:-1])
print(s[ ::-3])
print(s[-2:-5:-1])
print(s[4:2:-1])
print(s[0:2:-1])
print(s[ :: ])
print(s[ :-3: ])
print(s[ :-4:])
print(s[-2::])
print(s[-4::])
print(s[4:-2:-1])